---
# Blog applications

version: '3.8'

x-vpc:
  Properties:
    VpcCidr: 172.23.0.0/24
    EnableFlowLogs: True
    FlowLogsRoleBoundary: arn:aws:iam::aws:policy/AmazonVPCReadOnlyAccess

services:
  app03:
    image: app03
    networks:
      - custom01

networks:
  custom01:
    x-vpc: Custom01
