version: 0.2

env:
  variables:
    KNOWN_BUCKET: lambda-dev-eu-west-1
    PY_VERSION: 3.8
  git-credential-helper: yes

phases:
  install:
    runtime-versions:
      python: "$(echo $PY_VERSION)"
    commands:
      - export PY_FULL_VERSION=`python --version| awk '{print $NF}'`
      - export PATH=/root/.pyenv/versions/${PY_FULL_VERSION}/bin:${PATH}
      - pip --version || curl -s https://bootstrap.pypa.io/get-pip.py | python
      - pip install -r requirements.txt
      - pip install -r requirements_dev.txt
      - python setup.py install
  build:
    commands:
      - echo "Executing behave"
      - if ! [ -d reports ]; then mkdir reports ; fi
      - if ! [ -d coverage ]; then mkdir coverage ; fi
      - make coverage

artifacts:
  files:
    - '*.yml'
    - '*.json'
  base-directory: outputs
  name: outputs

reports:
  composex-tests:
    files:
      - "*.xml"
    base-directory: reports
    file-format: JunitXml
  composex-coverage:
    files:
      - "coverage.xml"
    base-directory: coverage
    file-format: COBERTURAXML
