version: 0.2

env:
  variables:
    KNOWN_BUCKET: lambda-dev-eu-west-1
    PY_VERSION: 3.8
  git-credential-helper: yes

phases:
  install:
    runtime-versions:
      python: "$(echo $PY_VERSION)"
    commands:
      - export PY_FULL_VERSION=`python --version| awk '{print $NF}'`
      - export LC_ALL="en_US.UTF-8"
      - export LC_CTYPE="en_US.UTF-8"
      - find / -name "python3.6*" -executable -type l -exec unlink {} +
      - export PATH=/root/.pyenv/versions/${PY_FULL_VERSION}/bin:${PATH}
      - pip --version || curl -s https://bootstrap.pypa.io/get-pip.py | python
      - pip install -r requirements.txt
      - pip install -r requirements_buildspec.txt
      - python setup.py install
  pre_build:
    commands:
      - make test
      - make lint
  build:
    commands:
      - mkdir -p ${PWD}/outputs
      - ecs_composex --help || echo $PATH && which python
      - ecs_composex-vpc -d outputs -o vpc_standalone.yml -b ${KNOWN_BUCKET} --no-upload
      - ecs_composex-vpc -f tests/services_with_queues.yml -d outputs -o vpc_standalone_with_input.yml -b ${KNOWN_BUCKET} --no-upload
      - ecs_composex-compute -d outputs -o compute_standalone.yml -b ${KNOWN_BUCKET} --no-upload
      - ecs_composex-compute -f tests/services_with_queues.yml -d outputs -o compute_standalone_with_input.yml -b ${KNOWN_BUCKET} --no-upload
      - ecs_composex --create-vpc --create-cluster -f tests/services_with_queues.yml -d outputs -o aio.yml -b ${KNOWN_BUCKET} --no-upload
      - ecs_composex --create-vpc --create-cluster -f tests/all_features.yml -d outputs -o all_features.yml -b ${KNOWN_BUCKET} --no-upload
      - ecs_composex --create-vpc --create-cluster -f tests/rds_only.yml -d outputs -o rds_only.yml -b ${KNOWN_BUCKET}

  post_build:
    commands:
      - echo "Executing behave"
      - if ! [ -d reports ]; then mkdir reports ; fi
      - behave --junit

artifacts:
  files:
    - '*.yml'
    - '*.json'
  base-directory: outputs
  name: outputs

reports:
  composexbehave:
    files:
      - "*.xml"
    base-directory: reports
    file-format: JunitXml
