version: 0.2

env:
  variables:
    KNOWN_BUCKET: lambda-dev-eu-west-1
    PY_VERSION: 3.8
  git-credential-helper: yes

phases:
  install:
    runtime-versions:
      python: "$(echo $PY_VERSION)"
    commands:
      - export PY_FULL_VERSION=`python --version| awk '{print $NF}'`
      - export PATH=/root/.pyenv/versions/${PY_FULL_VERSION}/bin:${PATH}
      - pip --version || curl -s https://bootstrap.pypa.io/get-pip.py | python
      - pip install -r requirements_dev.txt
      - python setup.py install
      - python setup.py develop
  pre_build:
    commands:
      - make test
      - make test-all

  build:
    commands:
      - mkdir -p ${PWD}/outputs
      - ecs_composex --help || echo $PATH && which python
      - ecs_composex-vpc -d outputs -o vpc_standalone.yml
      - ecs_composex-vpc -f tests/services_with_queues.yml -d outputs -o vpc_standalone_with_input.yml
      - ecs_composex-compute -d outputs -o compute_standalone.yml
      - ecs_composex-compute -f tests/services_with_queues.yml -d outputs -o compute_standalone_with_input.yml
      - ecs_composex --create-vpc --create-cluster -f tests/services_with_queues.yml -d outputs -o aio.yml

artifacts:
  files:
    - '*.yml'
    - '*.json'
  base-directory: outputs
  name: outputs
