version: 0.2

env:
  variables:
    KNOWN_BUCKET: lambda-dev-eu-west-1

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip --version || curl -s https://bootstrap.pypa.io/get-pip.py | python
      - pip install -r requirements_dev.txt
      - python setup.py install
  pre_build:
    commands:
      - make test
      - make test-all

  build:
    commands:
      - mkdir single-vpc
      - ecs_composex-vpc -f tests/services_with_queues.yml -o single-vpc/root.yml
