AWSTemplateFormatVersion: "2010-09-09"
Description: >-
  This CFN Template allows you to install the AWS CFN Macro as a Lambda Function to execute ECS Compose-X directly
  from within your AWS CloudFormation templates.

Transform:
  - AWS::Serverless-2016-10-31

Metadata:
  Maintainer: john@compose-x.io
  Version: 2021-01-25
  AWS::CloudFormation::Interface:
    ParmeterLabels:
      ECSComposeXMacroUri:
        default: ECS Compose-X Macro docker image URL
      TemplatesBucket:
        default: Bucket to store all rendered CloudFormation templates and config files.
    ParameterGroups:
      - Parameters:
          - ECSComposeXMacroUri
          - MemorySize
        Label:
          default: Lambda Settings
      - Parameters:
          - TemplatesBucket
        Label:
          default: ECS ComposeX Settings


Parameters:
  ECSComposeXMacroUri:
    Type: String
    Default: 518078317392.dkr.ecr.eu-west-1.amazonaws.com/compose-x-macro:nightly
  MemorySize:
    Type: Number
    Default: 128

  TemplatesBucket:
    Type: String
    Default: none

  PermissionsBoundary:
    Type: String
    Default: none

Conditions:
  AnyBucket: !Equals [ !Ref TemplatesBucket, "none" ]
  UseBoundary: !Not [ !Equals [ !Ref PermissionsBoundary, "none" ] ]

Resources:
  MacroFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      Tags:
        - Key: Name
          Value: lambda-compose-x-macro
        - Key: Usage
          Value: ECS Compose-X CFN macro
      PermissionsBoundary: !If
        - UseBoundary
        - !Ref PermissionsBoundary
        - !Ref AWS::NoValue
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - !Sub 'lambda.${AWS::URLSuffix}'
        Version: '2012-10-17'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/ResourceGroupsandTagEditorReadOnlyAccess
        - arn:aws:iam::aws:policy/ReadOnlyAccess
      Policies:
        - PolicyName: ECSComposeXAwsAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: CloudFormationAccess
                Effect: Allow
                Action:
                  - cloudformation:ValidateTemplate
                Resource:
                  - "*"
              - Sid: S3ObjectsAccess
                Effect: Allow
                Action:
                  - s3:PutObject*
                Resource: !If
                  - AnyBucket
                  - - "*"
                  - - !Sub "arn:${AWS::Partition}:s3:::${TemplatesBucket}/*"

  MacroLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      AutoPublishAlias: live
      Description: Lambda function to execute ECS Compose-X CFN Macro
      ImageUri: !Ref ECSComposeXMacroUri
      MemorySize: !Ref MemorySize
      Role: !GetAtt 'MacroFunctionRole.Arn'
      Timeout: 30
      FunctionName: !Sub "ecs-compose-x-macro-${AWS::Region}"
      PackageType: Image
      Tags:
        Name: !Sub "ecs-compose-x-macro-${AWS::Region}"
        Usage: ECS Compose-X CFN macro
  CloudFormationLogRole:
    Type: AWS::IAM::Role
    Properties:
      Tags:
        - Key: Name
          Value: CFN Macro Logging role
        - Key: Usage
          Value: ECS Compose-X
      Policies:
        - PolicyName: 'AllowLoggingForMacro'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - logs:PutLogEvents
                  - logs:CreateLogStream
                Effect: Allow
                Resource: [ !GetAtt 'CloudFormationLogGroup.Arn' ]
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - !Sub 'cloudformation.${AWS::URLSuffix}'

  CloudFormationMacro:
    Type: AWS::CloudFormation::Macro
    Properties:
      Description: Macro for ECS ComposeX embedded in CFN
      FunctionName: !Ref MacroLambdaFunction
      LogGroupName: !Ref CloudFormationLogGroup
      LogRoleARN: !GetAtt 'CloudFormationLogRole.Arn'
      Name: compose-x

  CloudFormationLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub 'cloudformation/macro/compose-x'
      RetentionInDays: 14
