version: '3.8'
x-kms:
  keyA:
    Properties: {}
    Services:
      bignicefamily:
        Access: EncryptDecrypt
    Settings:
      Alias: alias/keyA
  keyC:
    Lookup:
      Tags:
        - name: cicd
        - costcentre: lambda
    Services:
      app03:
        Access: EncryptDecrypt
      bignicefamily:
        Access: DecryptOnly
x-sqs:
  queueA: {}
  queueB:
    Properties:
      KmsMasterKeyId: x-kms::keyC
      RedrivePolicy:
        deadLetterTargetArn: queueA
        maxReceiveCount: 10
    Services:
      bignicefamily:
        Access: RWMessages
  queueC:
    Properties:
      FifoQueue: true
    Services:
      rproxy:
        Access: RWMessages
      youtoo:
        Access: RWMessages
  queueD:
    Properties:
      KmsMasterKeyId: x-kms::keyA
    Services:
      app01:
        Access: RWMessages
      app03:
        Access: RWMessages
  queueE:
    Properties: {}
    Services:
      bignicefamily:
        Access: RWMessages
        Scaling:
          ScaleInCooldown: 120
          ScaleOutCooldown: 60
          Steps:
            - Count: 1
              LowerBound: 0
              UpperBound: 10
            - Count: 2
              LowerBound: 10
              UpperBound: 20
            - Count: 5
              LowerBound: 20
  queueF:
    Lookup:
      Tags:
        - useless: 'yes'
        - costcentre: lambda
    Properties: {}
    Services:
      app03:
        Access: RWMessages
        ReturnValues:
          QueueName: QUEUE_F_NAME
        Scaling:
          ScaleInCooldown: 120
          ScaleOutCooldown: 60
          Steps:
            - Count: 1
              LowerBound: 0
              UpperBound: 10
            - Count: 2
              LowerBound: 10
              UpperBound: 20
            - Count: 5
              LowerBound: 20
      bignicefamily:
        Access: RWMessages
        ReturnValues:
          QueueName: QUEUE_F_NAME
