version: 0.2

env:
  variables:
    PY_VERSION: 3.8
  git-credential-helper: yes

phases:
  install:
    runtime-versions:
      python: "$(echo $PY_VERSION)"
    commands:
      - (pip --version && pip install pip -U)|| curl -s https://bootstrap.pypa.io/get-pip.py | python
      - pip install -r requirements.txt
      - pip install -r requirements_dev.txt
      - python setup.py install
  build:
    commands:
      - echo "Executing behave"
      - if ! [ -d reports ]; then mkdir reports ; else rm -rf reports/* ; fi
      - if ! [ -d coverage ]; then mkdir coverage ; else rm -rf coverage/* ; fi
      - make codebuild

reports:
  composex-tests:
    files:
      - "*.xml"
    base-directory: reports
    file-format: JunitXml
  composex-coverage:
    files:
      - "coverage.xml"
    base-directory: coverage
    file-format: COBERTURAXML
