version: 0.2

env:
  variables:
    PY_VERSION: 3.8
  git-credential-helper: yes

phases:
  install:
    runtime-versions:
      python: "$(echo $PY_VERSION)"
    commands:
      - (pip --version && pip install pip -U) || curl -s https://bootstrap.pypa.io/get-pip.py | python
      - pip install -r requirements_dev.txt
  build:
    commands:
      - echo "Building nightly docs"
      - make nightly-docs
      - aws cloudfront create-invalidation --distribution-id ${DISTRIBUTION_ID} --paths "/*"
