version: "3.8"
services:
  py37:
    build:
      dockerfile: Dockerfile
      context: ../
      args:
        SRC_TAG: "3.7.20210113"
        ARCH: "-${ARCH}"
    image: ${REGISTRY_URI}compose-x:${SUFFIX:-main}-py37${ARCH}

  py38:
    build:
      dockerfile: Dockerfile
      context: ../
      args:
        SRC_TAG: "3.8.20210113"
        ARCH: "-${ARCH}"
    image: ${REGISTRY_URI}compose-x:${SUFFIX:-main}-py38${ARCH}
