---
# Docker compose file for the purpose of building images
version: "3.8"
services:
  py310:
    build:
      dockerfile: cli.Dockerfile
      context: ../
      args:
        ARCH: "-${ARCH}"
    image: ${REGISTRY_URI}compose-x:${SUFFIX:-main}-py310-${ARCH}
