AWSTemplateFormatVersion: "2010-09-09"
Transform:
  - AWS::Serverless-2016-10-31
Description: >-
  Template to deploy Lambda Layer version
Resources:
  LambdaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.7
        - python3.8
      ContentUri: ../layer.zip
      Description: ECS Compose-X Lambda Layer
      LayerName: ecs_composex
      LicenseInfo: GPLv3
      RetentionPolicy: Retain

  LayerPermissions:
    Type: AWS::Lambda::LayerVersionPermission
    Properties:
      Action: lambda:GetLayerVersion
      LayerVersionArn: !Ref LambdaLayer
      OrganizationId: "*"
      Principal: "*"


Outputs:
  LayerVersion:
    Value: !Ref LambdaLayer
