---
# RDS Use-case.

version: '3.8'
services:
  rproxy:
    image: 373709687836.dkr.ecr.eu-west-1.amazonaws.com/blog-app-01-rproxy:latest
    ports:
      - 80:80
      - 443:443
    deploy:
      replicas: 6
      resources:
        reservations:
          cpus: "0.1"
          memory: "32M"
        limits:
          cpus: "0.25"
          memory: "64M"
      labels:
        - "ecs.task.family=app01"
    x-configs:
      network:
        is_public: True
        lb_type: application
    depends_on:
      - app

x-rds:
  dbA:
    Properties:
      Engine: "aurora-postgresql"
      EngineVersion: "11.7"
    Settings:
      EnvNames:
        - DBA
    Services:
      - name: app01
        access: RW

  dbB:
    Properties: {}
    Settings: {}
    Services:
      - name: app
        access: RW
    Lookup:
      cluster:
        Name: database-1
        Tags:
          - serverless: "True"
      secret:
        Name: GHToken
        Tags:
          - useless: "yes"
