---
# Blog applications

version: '3.8'

services:
  rproxy:
    image: 373709687836.dkr.ecr.eu-west-1.amazonaws.com/blog-app-01-rproxy:latest
    ports:
      - 80:80
    deploy:
      replicas: 1
      resources:
        reservations:
          cpus: "0.1"
          memory: "32M"
        limits:
          cpus: "0.25"
          memory: "64M"
      labels:
        ecs.task.family: app01
    x-configs:
      network:
        IsPublic: True
        lb_type: application
    depends_on:
      - app01
  app01:
    image: 373709687836.dkr.ecr.eu-west-1.amazonaws.com/blog-app-01:appmesh
    ports:
      - 5000
    deploy:
      resources:
        reservations:
          cpus: "0.25"
          memory: "64M"
      labels:
        ecs.task.family: app01
    environment:
      LOGLEVEL: DEBUG
    x-configs:
      use_xray: True
    links:
      - app03:dateteller

  app02:
    image: 373709687836.dkr.ecr.eu-west-1.amazonaws.com/blog-app-02:appmesh
    ports:
      - 5000
    deploy:
      resources:
        reservations:
          cpus: "0.25"
      labels:
        ecs.task.family: app02
    environment:
      LOGLEVEL: DEBUG
    x-configs:
      use_xray: True

  app03:
    image: 373709687836.dkr.ecr.eu-west-1.amazonaws.com/blog-app-02:appmesh
    ports:
      - 5000
    deploy:
      resources:
        reservations:
          cpus: "0.25"
      labels:
        ecs.task.family: app03
    environment:
      LOGLEVEL: DEBUG
    x-configs:
      use_xray: True


x-tags:
  owner: johnpreston
  contact: john@compose-x.io

x-appmesh:
  Properties:
    MeshName: test-shared-mesh
  Settings:
    nodes:
      - name: app03
        protocol: http
      - name: app02
        protocol: http
      - name: app01
        protocol: http
        backends:
          - dateteller # Points to the dateteller service, not router!
    routers:
      - name: dateteller
        listener:
          port: 5000
          protocol: http
        routes:
          http:
            - match:
                prefix: /date
                method: GET
                scheme: http
              nodes:
                - name: app02
                  weight: 1
            - match:
                prefix: /date/utc
              nodes:
                - name: app03
                  weight: 1
    services:
      - name: api
        node: app01
      - name: dateteller
        router: dateteller

x-dns:
  PrivateNamespace:
    Name: mycluster.lan
  PublicNamespace:
    Name: lambda-my-aws.io

x-vpc:
  Create:
    VpcCidr: 10.0.0.24

x-configs:
  composex:
    iam:
      PermissionsBoundary: arn:aws:iam::aws:policy/PowerUser
