---
# Blog applications

version: '3.8'

services:
  rproxy:
    image: 373709687836.dkr.ecr.eu-west-1.amazonaws.com/blog-app-01-rproxy:latest
    ports:
      - 80:80
    deploy:
      replicas: 1
      resources:
        reservations:
          cpus: "0.1"
          memory: "32M"
        limits:
          cpus: "0.25"
          memory: "64M"
      labels:
        ecs.task.family: app01
    x-configs:
      network:
        lb_type: application
    depends_on:
      - app01
  app01:
    image: 373709687836.dkr.ecr.eu-west-1.amazonaws.com/blog-app-01:appmesh
    ports:
      - 5000
    deploy:
      resources:
        reservations:
          cpus: "0.25"
          memory: "64M"
      labels:
        ecs.task.family: app01
    environment:
      LOGLEVEL: DEBUG
    x-configs:
      use_xray: True
    links:
      - app03:dateteller

  app02:
    image: 373709687836.dkr.ecr.eu-west-1.amazonaws.com/blog-app-02:appmesh
    ports:
      - 5000
    deploy:
      resources:
        reservations:
          cpus: "0.25"
          memory: "64M"
      labels:
        ecs.task.family: app02
    environment:
      LOGLEVEL: DEBUG
    x-configs:
      use_xray: True

  app03:
    image: 373709687836.dkr.ecr.eu-west-1.amazonaws.com/blog-app-02:appmesh
    ports:
      - 5000
    deploy:
      resources:
        reservations:
          cpus: "0.25"
          memory: "64M"
      labels:
        ecs.task.family: app03
    environment:
      LOGLEVEL: DEBUG
    x-configs:
      use_xray: True


x-tags:
  owner: johnpreston
  contact: john@compose-x.io

x-appmesh:
  Properties:
    MeshName: test-shared-mesh
  Settings:
    Nodes:
      - Name: app03
        Protocol: Http
      - Name: app02
        Protocol: Http
      - Name: app01
        Protocol: Http
        Backends:
          - dateteller # Points to the dateteller service, not router!
    Routers:
      - Name: dateteller
        Listener:
          Port: 5000
          Protocol: Http
        Routes:
          Http:
            - Match:
                Prefix: /date
                Method: GET
                Scheme: http
              Nodes:
                - Name: app02
                  Weight: 1
            - Match:
                Prefix: /date/utc
              Nodes:
                - Name: app03
                  Weight: 1
    Services:
      - Name: api
        Node: app01
      - Name: dateteller
        Router: dateteller
