---
# Blog applications

version: '3.8'

services:
  rproxy:
    ports:
      - 80:80
    deploy:
      replicas: 1
      labels:
        ecs.task.family: app01
    x-configs:
      use_xray: True
  app01:
    ports:
      - 5000
      - 5001:5000
    deploy:
      labels:
        ecs.task.family: app01

  app03:
    x-configs:
      logging:
        logs_retention_period: 60
    ports:
      - 5000
    deploy:
      resources:
        reservations:
          cpus: "0.25"
      labels:
        ecs.task.family: app03

  app04:
    ports: []
    image: nginx

x-tags:
  owner: johnpreston
  contact: john@lambda-my-aws.io
  another: one

x-appmesh:
  Properties:
    MeshName: root
  Settings:
    nodes:
      - name: app03
        protocol: http
      - name: app02
        protocol: http
      - name: app01
        protocol: http
        backends:
          - dateteller # Points to the dateteller service, not router!
    routers:
      - name: dateteller
        listener:
          port: 5000
          protocol: http
        routes:
          http:
            - match:
                prefix: /date
                method: GET
                scheme: http
              nodes:
                - name: app02
                  weight: 1
            - match:
                prefix: /date/utc
              nodes:
                - name: app03
                  weight: 1
    services:
      - name: api
        node: app01
      - name: dateteller
        router: dateteller

x-dns:
  PrivateNamespace:
    Name: mycluster.lan
  PublicNamespace:
    Name: lambda-my-aws.io

x-vpc:
  Create:
    VpcCidr: 10.0.0.0/24

x-cluster: dev
