---
# Blog applications

version: '3.8'

x-configs:
  app:
    network:
      use_cloudmap: True

services:
  rproxy:
    image: 373709687836.dkr.ecr.eu-west-1.amazonaws.com/blog-app-01-rproxy:latest
    ports:
      - 80:80
    deploy:
      replicas: 2
      resources:
        reservations:
          cpus: "0.1"
          memory: "32M"
        limits:
          cpus: "0.25"
          memory: "64M"
      labels:
        ecs.task.family: bignicefamily
    x-configs:
      network:
        is_public: True
        lb_type: application
    depends_on:
      - app01
  app01:
    image: 373709687836.dkr.ecr.eu-west-1.amazonaws.com/blog-app-01:appmesh
    ports:
      - 5000
    deploy:
      resources:
        reservations:
          cpus: "0.25"
          memory: "64M"
      labels:
        ecs.task.family: bignicefamily
    environment:
      LOGLEVEL: DEBUG
    x-configs:
      use_xray: True
      network:
        ingress:
          myself: True
          aws_sources:
            - type: SecurityGroup
              id: sg-abcd
            - type: PrefixList
              id: pl-abcd
    links:
      - app03:dateteller

  app02:
    secrets:
      - testsecret
    image: 373709687836.dkr.ecr.eu-west-1.amazonaws.com/blog-app-02:latest
    ports:
      - 5000
    deploy:
      resources:
        reservations:
          cpus: "0.25"
          memory: "64M"
    environment:
      LOGLEVEL: DEBUG
    x-configs:
      use_xray: True

  app03:
    image: 373709687836.dkr.ecr.eu-west-1.amazonaws.com/blog-app-02:latest
    secrets:
      - undefined
      - source: testsecret
    ports:
      - 5000
    deploy:
      resources:
        reservations:
          cpus: "0.25"
          memory: "64M"
    environment:
      LOGLEVEL: DEBUG
    x-configs:
      network:
        lb_type: network
        is_public: True
      use_xray: True
      iam:
        boundary: arn:aws:iam::aws:policy/ViewOnly
        policies:
          - document:
              Version: 2012-10-17
              Statement:
                - Sid: SomethingInteresting
                  Action:
                    - cloudwatch:PutMetric*
                  Resource:
                    - "*"
                  Effect: Allow
        managed_policies:
          - arn:aws:iam::aws:policy/AdministratorAccess

x-appmesh:
  Properties:
    MeshName: root
  Settings:
    nodes:
      - name: app03
        protocol: http
      - name: app02
        protocol: http
      - name: bignicefamily
        protocol: http
        backends:
          - dateteller # Points to the dateteller service, not router!
    routers:
      - name: dateteller
        listener:
          port: 5000
          protocol: http
        routes:
          http:
            - match:
                prefix: /date
                method: GET
                scheme: http
              nodes:
                - name: app02
                  weight: 1
            - match:
                prefix: /date/utc
              nodes:
                - name: app03
                  weight: 1
    services:
      - name: api
        node: bignicefamily
      - name: dateteller
        router: dateteller

x-dns:
  PrivateNamespace:
    Name: home.lan
  PublicNamespace:
    Name: lambda-my-aws.io

x-sqs:
  queueA:
    Properties:
      QueueName: abcd
      RedrivePolicy:
        deadLetterTargetArn: queueB
        maxReceiveCount: 4
    Settings:
      EnvNames:
        - QUEUEA
    Services:
      - name: app03
        access: RWMessages

  queueB:
    Properties:
      QueueName: xyz
    Settings:
      EnvNames:
        - QUEUEB
    Services:
      - name: rproxy
        access: RWMessages

x-sns:
  Topics:
    topicA:
      Properties: {}
      Services:
        - name: bignicefamily
          access: Publish
        - name: app03
          access: Publish
    topicB:
      Properties:
        Subscription:
          - Endpoint: queueB
            Protocol: sqs

x-rds:
  dbA:
    Properties:
      Engine: "aurora-mysql"
      EngineVersion: "5.7.12"
    Settings:
      EnvNames:
        - DBA
    Services:
      - name: bignicefamily
        access: RW
      - name: app03
        access: RW

x-dynamodb:
  tableA:
    Properties:
      AttributeDefinitions:
        - AttributeName: "ArtistId"
          AttributeType: "S"
        - AttributeName: "Concert"
          AttributeType: "S"
        - AttributeName: "TicketSales"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "ArtistId"
          KeyType: "HASH"
        - AttributeName: "Concert"
          KeyType: "RANGE"
      GlobalSecondaryIndexes:
        - IndexName: "GSI"
          KeySchema:
            - AttributeName: "TicketSales"
              KeyType: "HASH"
          Projection:
            ProjectionType: "KEYS_ONLY"
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
    Services:
      - name: app03
        access: RW
      - name: bignicefamily
        access: RO

  tableB:
    Properties:
      AttributeDefinitions:
        - AttributeName: "Album"
          AttributeType: "S"
        - AttributeName: "Artist"
          AttributeType: "S"
        - AttributeName: "Sales"
          AttributeType: "N"
        - AttributeName: "NumberOfSongs"
          AttributeType: "N"
      KeySchema:
        - AttributeName: "Album"
          KeyType: "HASH"
        - AttributeName: "Artist"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      GlobalSecondaryIndexes:
        - IndexName: "myGSI"
          KeySchema:
            - AttributeName: "Sales"
              KeyType: "HASH"
            - AttributeName: "Artist"
              KeyType: "RANGE"
          Projection:
            NonKeyAttributes:
              - "Album"
              - "NumberOfSongs"
            ProjectionType: "INCLUDE"
          ProvisionedThroughput:
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"
        - IndexName: "myGSI2"
          KeySchema:
            - AttributeName: "NumberOfSongs"
              KeyType: "HASH"
            - AttributeName: "Sales"
              KeyType: "RANGE"
          Projection:
            NonKeyAttributes:
              - "Album"
              - "Artist"
            ProjectionType: "INCLUDE"
          ProvisionedThroughput:
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"
      LocalSecondaryIndexes:
        - IndexName: "myLSI"
          KeySchema:
            - AttributeName: "Album"
              KeyType: "HASH"
            - AttributeName: "Sales"
              KeyType: "RANGE"
          Projection:
            NonKeyAttributes:
              - "Artist"
              - "NumberOfSongs"
            ProjectionType: "INCLUDE"

    Services:
      - name: app02
        access: RW
    Settings:
      EnvNames:
        - TABLEB
        - tableb

  tableC:
    Lookup:
      Tags:
        - name: tableC
    Services:
      - name: app02
        access: RO

x-kms:
  keyA:
    Properties: {}
    Settings:
      Alias: alias/keyA
    Services:
      - name: bignicefamily
        access: EncryptDecrypt

  keyB:
    Properties:
      PendingWindowInDays: 14
    Settings:
      Alias: keyB
    Services:
      - name: app02
        access: SQS
      - name: app03
        access: EncryptOnly
      - name: bignicefamily
        access: DecryptOnly

x-tags:
  costcentre: abcd
  contact: you@me.com

x-cluster:
  Properties:
    CapacityProviders:
      - FARGATE
      - FARGATE_SPOT
    ClusterName: testabcd
    DefaultCapacityProviderStrategy:
      - CapacityProvider: FARGATE_SPOT
        Weight: 4
        Base: 2
      - CapacityProvider: FARGATE
        Weight: 1

secrets:
  testsecret:
    external: true
    x-secrets:
      Name: /path/to/my/secret

  testabcdsecret:
    file: /dev/null
    x-secrets:
      Name: /nowhere
