services:
  app01:
    x-iam:
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - cloudwatch:PutMetricData
                Effect: Allow
                Resource:
                  - '*'
                Sid: AllowPublishMetricsToCw
            Version: '2012-10-17'
          PolicyName: AllowPublishToCw
    x-logging:
      CreateLogGroup: false
      RetentionInDays: 42
    x-network:
      Ingress:
        AwsSources:
          - Id: pl-6da54004
            Type: PrefixList
        Myself: false
    x-xray: false
  app02:
    x-iam:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      PermissionsBoundary: arn:aws:iam::aws:policy/AdministratorAccess
    x-scaling:
      Range: 1-5
      TargetScaling:
        DisableScaleIn: true
        MemoryTarget: 30
    x-xray: false
  app03:
    labels:
      Java_EMF_Metrics: 'true'
    x-logging:
      RetentionInDays: 42
    x-network:
      Ingress:
        ExtSources:
          - Description: ANYWHERE
            IPv4: 0.0.0.0/0
        Myself: false
    x-prometheus:
      ContainersInsights:
        CollectForAppMesh: false
        CollectForJavaJmx: true
        CustomRules:
          - EmfProcessors:
              - dimensions:
                  - - ClusterName
                    - TaskDefinitionFamily
                label_matcher: app03
                metric_selectors:
                  - ^startsEnds$
                source_labels:
                  - container_name
            ExporterPort: 1234
        ScrapingConfiguration:
          Interval: 15s
          Timeout: 5s
    x-scaling:
      Range: 1-10
      TargetScaling:
        CpuTarget: 50
  rproxy:
    x-iam:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/ReadOnlyAccess
    x-scaling:
      Range: 0-2
      TargetScaling:
        CpuTarget: 50
    x-xray: true
version: '3.8'
