---
# ComposeX env file with ElasticCache definitions


services:
  nginx:
    image: nginx

x-elasticache:
  cache01:
    Properties:
      AutoMinorVersionUpgrade: 'true'
      Engine: memcached
      EngineVersion: 1.6.6
      CacheNodeType: cache.t3.small
      NumCacheNodes: 1
    Services:
      - name: app03
        access: RW

  cache-02:
    MacroParameters:
      Engine: redis
      EngineVersion: 6.x
    Services:
      - name: app03
        access: RW

  cache03:
    Properties:
        ReplicationGroupDescription: my description
        NumCacheClusters: '2'
        Engine: redis
        CacheNodeType: cache.m3.medium
        AutoMinorVersionUpgrade: 'true'
        AutomaticFailoverEnabled: 'true'
        CacheSubnetGroupName: subnetgroup
        EngineVersion: 6.x
        PreferredMaintenanceWindow: 'wed:09:25-wed:22:30'
        SnapshotRetentionLimit: '4'
        SnapshotWindow: '03:30-05:30'
    Services:
      - name: app02
        access: RW
