---
# Blog applications

version: '3.8'
services:
  rproxy:
    image: ${IMAGE:-nginx}
    ports:
      - 80:80
    deploy:
      labels:
        ecs.task.family: bignicefamily,youtoo
      replicas: 1
      resources:
        reservations:
          cpus: "0.1"
          memory: "32M"
        limits:
          cpus: "0.25"
          memory: "64M"
    depends_on:
      - app01
      - app02

  app01:
    image: ${IMAGE:-nginx}
    secrets:
      - zyx
    ports:
      - 5000
    deploy:
      labels:
        ecs.task.family: bignicefamily
      resources:
        reservations:
          cpus: "0.25"
          memory: "64M"
    environment:
      LOGLEVEL: DEBUG
      SHELLY: ${SHELL}
      TERMY: "$TERM"
    links:
      - app03:dateteller

  app02:
    image: ${IMAGE:-nginx}
    secrets:
      - zyx
    ports:
      - 5000
    deploy:
      replicas: 2
      labels:
        ecs.task.family: youtoo
      resources:
        reservations:
          cpus: "0.25"
          memory: "64M"
    environment:
      LOGLEVEL: DEBUG
    healthcheck:
      test:
        - CMD
        - curl
        - localhost:5000/ping
      interval: 30
      retries: 3

  app03:
    image: ${IMAGE:-nginx}
    ports:
      - 5000
    deploy:
      resources:
        reservations:
          cpus: "0.25"
          memory: "64M"
    environment:
      LOGLEVEL: DEBUG
    volumes:
      - shared-images
    secrets:
      - abcd
      - zyx
      - john


volumes:
  shared-images: {}

secrets:
  abcd: {}
  zyx:
    x-secrets:
      Name: SFTP/smicuser
  john:
    x-secrets:
      Name: SFTP/asl-cscs-files-dev
      LinksTo:
        - EcsExecutionRole
        - EcsTaskRole
