---
# Blog applications

version: '3.8'

x-configs:
  app:
    network:
      use_cloudmap: True

services:
  rproxy:
    image: 373709687836.dkr.ecr.eu-west-1.amazonaws.com/blog-app-01-rproxy:latest
    ports:
      - 80:80
    deploy:
      replicas: 2
      resources:
        reservations:
          cpus: "0.1"
          memory: "32M"
        limits:
          cpus: "0.25"
          memory: "64M"
      labels:
        ecs.task.family: app01
    x-configs:
      network:
        is_public: True
        lb_type: application
    depends_on:
      - app01
  app01:
    image: 373709687836.dkr.ecr.eu-west-1.amazonaws.com/blog-app-01:appmesh
    ports:
      - 5000
    deploy:
      resources:
        reservations:
          cpus: "0.25"
          memory: "64M"
      labels:
        ecs.task.family: app01
    environment:
      LOGLEVEL: DEBUG
    x-configs:
      use_xray: True
      network:
        ingress:
          myself: True
          aws_sources:
            - type: SecurityGroup
              id: sg-abcd
            - type: PrefixList
              id: pl-abcd
    links:
      - app03:dateteller

  app02:
    image: 373709687836.dkr.ecr.eu-west-1.amazonaws.com/blog-app-02:latest
    ports:
      - 5000
    deploy:
      resources:
        reservations:
          cpus: "0.25"
          memory: "64M"
      labels:
        ecs.task.family: app02
    environment:
      LOGLEVEL: DEBUG
    x-configs:
      use_xray: True

  app03:
    image: 373709687836.dkr.ecr.eu-west-1.amazonaws.com/blog-app-02:latest
    ports:
      - 5000
    deploy:
      resources:
        reservations:
          cpus: "0.25"
          memory: "64M"
      labels:
        ecs.task.family: app03
    environment:
      LOGLEVEL: DEBUG
    x-configs:
      use_xray: True

x-tags:
  owner: johnpreston
  contact: john@lambda-my-aws.io

x-vpc:
  Use:
    VpcId: vpc-02cdb0d58698cd10f
    AppSubnets:
      - subnet-05ac0a6a5dcb126c9
      - subnet-07afbd5c4bea83c86
      - subnet-0ef4b7eb701f5fca4
    StorageSubnets: ['subnet-0c71f6e048372710c', 'subnet-0dd3df2ee67021bd8', 'subnet-022fd25f01655d2c7']
    PublicSubnets: 'subnet-0a28abea71c010d8c,subnet-0d48c03966643eea6,subnet-033a946a3b0cf4e58'

x-cluster:
  Use: dev
