secrets:
  abcd: {}
  john:
    x-secrets:
      Name: /cicd/shared/github.com/token
  zyx: {}
services:
  app01:
    cap_add:
      - ALL
    deploy:
      labels:
        ecs.ephemeral.storage: 65
        ecs.task.family: bignicefamily
      resources:
        reservations:
          cpus: '0.25'
          memory: 1GB
      update_config:
        failure_action: rollback
    environment:
      LOGLEVEL: DEBUG
      SHELLY: /bin/bash
      TERMY: screen
    image: nginx
    links:
      - app03:dateteller
    logging:
      driver: awslogs
      options:
        awslogs-create-group: 'true'
        awslogs-group: a-custom-name
    ports:
      - mode: awsvpc
        protocol: tcp
        published: 5000
        target: 5000
    secrets:
      - zyx
    sysctls:
      - net.core.somaxconn=2048
      - net.ipv4.tcp_syncookies=1
    volumes:
      - target: /tmp
        tmpfs:
          size: 1024
        type: tmpfs
      - normal-vol:/var/tmp/shared
      - some-volume:/var/anotherpath:ro
    x-iam:
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - cloudwatch:PutMetricData
                Effect: Allow
                Resource:
                  - '*'
                Sid: AllowPublishMetricsToCw
            Version: '2012-10-17'
          PolicyName: AllowPublishToCw
    x-logging:
      CreateLogGroup: false
      RetentionInDays: 42
    x-network:
      Ingress:
        AwsSources:
          - Id: pl-6da54004
            Type: PrefixList
        Myself: false
      IsPublic: false
      UseCloudmap: true
    x-scaling:
      Range: 1-4
    x-xray: false
  app02:
    depends_on:
      - app01
      - bignicefamily
    deploy:
      labels:
        ecs.ephemeral.storage: 12128GB
        ecs.task.family: youtoo
      replicas: 2
      resources:
        reservations:
          cpus: '0.1'
          memory: 64000kB
      update_config:
        failure_action: pause
    environment:
      LOGLEVEL: DEBUG
    healthcheck:
      interval: 1m30s
      retries: 3
      start_period: 1h
      test:
        - CMD
        - curl
        - localhost:5000/ping
      timeout: 10s
    image: nginx
    ports:
      - mode: awsvpc
        protocol: tcp
        published: 5000
        target: 5000
    secrets:
      - zyx
    tmpfs: /run
    volumes:
      - source: some-volume
        target: /app/data
        type: volume
    x-iam:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      PermissionsBoundary: arn:aws:iam::aws:policy/AdministratorAccess
    x-scaling:
      Range: 1-5
      TargetScaling:
        CpuTarget: 88
        DisableScaleIn: true
    x-xray: false
  app03:
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    cap_drop:
      - SYS_ADMIN
    deploy:
      labels:
        ecs.ephemeral.storage: 20
        testing: value
      resources:
        reservations:
          cpus: '0.25'
          memory: 134217728b
    environment:
      LOGLEVEL: DEBUG
    image: nginx
    ports:
      - mode: awsvpc
        protocol: tcp
        published: 5000
        target: 5000
    secrets:
      - abcd
      - zyx
      - john
    sysctls:
      net.core.somaxconn: 1024
      net.ipv4.tcp_syncookies: 0
    tmpfs:
      - /run
      - /tmp
    ulimits:
      nofile:
        hard: 2048
        soft: 1024
      nproc: 512
    volumes:
      - /generated/volume/from/path
      - shared-images:/app/images
      - some-volume:/app/data:ro
    x-aws-max_percent: 150
    x-aws-min_percent: 50
    x-logging:
      RetentionInDays: 30
    x-network:
      Ingress:
        ExtSources:
          - IPv4: 0.0.0.0/0
            Name: ANYWHERE
        Myself: false
    x-scaling:
      Range: 1-10
  rproxy:
    depends_on:
      - app01
      - app02
    deploy:
      labels:
        ecs.ephemeral.storage: 175
        ecs.task.family: bignicefamily,youtoo
      replicas: 1
      resources:
        limits:
          cpus: '0.25'
          memory: 64M
        reservations:
          cpus: '0.1'
          memory: 32M
    image: nginx
    logging:
      driver: awslogs
      options:
        awslogs-region: us-east-1
    ports:
      - mode: awsvpc
        protocol: tcp
        published: 80
        target: 80
    volumes:
      - normal-vol:/tmp/shared
    x-iam:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/ReadOnlyAccess
    x-network:
      IsPublic: false
      UseCloudmap: true
    x-xray: true
version: '3.8'
volumes:
  normal-vol: {}
  shared-images: {}
  some-volume: {}
x-cloudmap:
  PrivateNamespace:
    Name: lambda.internal
x-tags:
  costcentre: lambda
