version: "3.1"
services:
  nginx:
    container_name: nginx-${SITE_NAME}
    build: ./docker/nginx/
    ports:
      - 80:80
    links:
      - phpfpm
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
  phpfpm:
    container_name: phpfpm-${SITE_NAME}
    build:
      context: .
      dockerfile: ./docker/phpfpm/Dockerfile
    ports:
      - 9000:9000
    links:
      - mysql
    volumes:
      - .:/var/www/html:cached
      - ./docker/phpfpm/phpfpm.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./logs/phpfpm:/var/log
    environment:
      - DATABASE_URL=mysql://${DB_USER}:${DB_PASS}@mysql:3306/${DB_NAME}
  mysql:
    container_name: mysql-${SITE_NAME}
    build: ./docker/mysql/
    restart: 'always'
    command: mysqld --lower_case_table_names=1
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql:cached
      - ./logs/mysql:/var/log/mysql:cached
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
